#theme: jekyll-theme-cayman
title: Christopher Kirkham
project-name: Christopher Kirkham
project-tagline: Interested in game development, AI, and music. BSc Hons Computer Science with Artificial Intelligence, University of Nottingham (2018).
